### ISSUE TITLE
Indentation in index.ejs

### ISSUE THREAD

**Issue by truered8** [youthcomputing/YouthComputingWebsite#9]
I think the Latest Works section of `index.ejs` has incorrect indentation:
```html
	<ul id="gtco-portfolio-list">
	<li class="two-third animate-box" data-animate-effect="fadeIn" 
	style="background-image: url(images/fuse2.jpg); ">
	<a href="fuse19" class="color-1">
		<div class="case-studies-summary">
			<span>Fuse 2019</span>
			<h2>Technology Expo of a Lifetime</h2>
		</div>
	</a>
</li>
```

**Comment by Dhvani35729** [comment]
@nirmitparikh8 , can you look into linting the files using ESLint and Prettier.

**Comment by nirmitparikh8** [comment]
> @nirmitparikh8 , can you look into linting the files using ESLint and Prettier.

Sure

**Comment by nirmitparikh8** [comment]
> > @nirmitparikh8 , can you look into linting the files using ESLint and Prettier.
> 
> Sure

I am having errors linting the file.

**Comment by Dhvani35729** [comment]
Fixed in latest commit.
